
FROM maven AS firststage
RUN apt install -y git
RUN mkdir /src/
WORKDIR /src/
RUN git clone https://github.com/spring-projects/spring-petclinic
WORKDIR /src/spring-projects/
RUN ./mvnw package

FROM openjdk:8
WORKDIR /usr/src/myapp
COPY --from=firststage /go/src/github.com/alexellis/href-counter/app .

CMD ["./app"]
